/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author User
 */
public class dlgAyuda extends javax.swing.JDialog {

    /**
     * Creates new form dlgAyuda
     */
    public dlgAyuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panInformacion = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAcercaDe = new javax.swing.JTextArea();
        btnIngles = new javax.swing.JButton();
        btnJapones = new javax.swing.JButton();
        btnFrances = new javax.swing.JButton();
        btnEspaniol = new javax.swing.JButton();
        lblLenguaje = new javax.swing.JLabel();
        btnInventario = new javax.swing.JButton();
        btnTrabajadores = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        btnCaja = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCajaimg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAyudaCaja = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        lblTrabajadoresimg = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAyudaTrabajadores = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        lblClientesimg = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAyudaClientes = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        lblInventarioimg = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAyudaInventario = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        lblCategoriaimg = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAyudaCategoria = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        lblFacturaimg = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAyudaFactura = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAcercaDe.setEditable(false);
        txtAcercaDe.setColumns(20);
        txtAcercaDe.setRows(5);
        txtAcercaDe.setOpaque(false);
        jScrollPane1.setViewportView(txtAcercaDe);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 750, 210));

        btnIngles.setText("Ingles");
        jPanel1.add(btnIngles, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 150, 30));

        btnJapones.setText("Japones");
        jPanel1.add(btnJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 150, 30));

        btnFrances.setText("Frances");
        jPanel1.add(btnFrances, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 150, 30));

        btnEspaniol.setText("Español");
        jPanel1.add(btnEspaniol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 150, 30));

        lblLenguaje.setText("Lenguaje :");
        jPanel1.add(lblLenguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 140, 30));

        btnInventario.setText("Inventario");
        jPanel1.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 150, 40));

        btnTrabajadores.setText("Trabajadores");
        jPanel1.add(btnTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 150, 40));

        btnClientes.setText("Clientes");
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 150, 40));

        btnCategoria.setText("Categoria");
        jPanel1.add(btnCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 150, 40));

        btnFactura.setText("Factura");
        jPanel1.add(btnFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 150, 40));

        btnCaja.setText("Caja ");
        jPanel1.add(btnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 150, 40));

        panInformacion.addTab("Acerca de ..", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCajaimg.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(lblCajaimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 720, 310));

        txtAyudaCaja.setEditable(false);
        txtAyudaCaja.setColumns(20);
        txtAyudaCaja.setRows(5);
        jScrollPane2.setViewportView(txtAyudaCaja);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 346, 720, 110));

        panInformacion.addTab("Caja", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTrabajadoresimg.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(lblTrabajadoresimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 720, 310));

        txtAyudaTrabajadores.setEditable(false);
        txtAyudaTrabajadores.setColumns(20);
        txtAyudaTrabajadores.setRows(5);
        jScrollPane3.setViewportView(txtAyudaTrabajadores);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 346, 720, 110));

        panInformacion.addTab("Trabajadores", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClientesimg.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.add(lblClientesimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 720, 310));

        txtAyudaClientes.setEditable(false);
        txtAyudaClientes.setColumns(20);
        txtAyudaClientes.setRows(5);
        jScrollPane4.setViewportView(txtAyudaClientes);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 346, 720, 110));

        panInformacion.addTab("Clientes ", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInventarioimg.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.add(lblInventarioimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 720, 310));

        txtAyudaInventario.setEditable(false);
        txtAyudaInventario.setColumns(20);
        txtAyudaInventario.setRows(5);
        jScrollPane5.setViewportView(txtAyudaInventario);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 346, 720, 110));

        panInformacion.addTab("Inventario", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCategoriaimg.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel6.add(lblCategoriaimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 720, 310));

        txtAyudaCategoria.setEditable(false);
        txtAyudaCategoria.setColumns(20);
        txtAyudaCategoria.setRows(5);
        jScrollPane6.setViewportView(txtAyudaCategoria);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 346, 720, 110));

        panInformacion.addTab("Categoria", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFacturaimg.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel7.add(lblFacturaimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 720, 310));

        txtAyudaFactura.setEditable(false);
        txtAyudaFactura.setColumns(20);
        txtAyudaFactura.setRows(5);
        jScrollPane7.setViewportView(txtAyudaFactura);

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 346, 720, 110));

        panInformacion.addTab("Factura", jPanel7);

        getContentPane().add(panInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 840, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgAyuda dialog = new dlgAyuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaja;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEspaniol;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnFrances;
    private javax.swing.JButton btnIngles;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnJapones;
    private javax.swing.JButton btnTrabajadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblCajaimg;
    private javax.swing.JLabel lblCategoriaimg;
    private javax.swing.JLabel lblClientesimg;
    private javax.swing.JLabel lblFacturaimg;
    private javax.swing.JLabel lblInventarioimg;
    private javax.swing.JLabel lblLenguaje;
    private javax.swing.JLabel lblTrabajadoresimg;
    private javax.swing.JTabbedPane panInformacion;
    private javax.swing.JTextArea txtAcercaDe;
    private javax.swing.JTextArea txtAyudaCaja;
    private javax.swing.JTextArea txtAyudaCategoria;
    private javax.swing.JTextArea txtAyudaClientes;
    private javax.swing.JTextArea txtAyudaFactura;
    private javax.swing.JTextArea txtAyudaInventario;
    private javax.swing.JTextArea txtAyudaTrabajadores;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnCaja() {
        return btnCaja;
    }

    public javax.swing.JButton getBtnCategoria() {
        return btnCategoria;
    }

    public javax.swing.JButton getBtnClientes() {
        return btnClientes;
    }

    public javax.swing.JButton getBtnEspaniol() {
        return btnEspaniol;
    }

    public javax.swing.JButton getBtnFactura() {
        return btnFactura;
    }

    public javax.swing.JButton getBtnFrances() {
        return btnFrances;
    }

    public javax.swing.JButton getBtnIngles() {
        return btnIngles;
    }

    public javax.swing.JButton getBtnInventario() {
        return btnInventario;
    }

    public javax.swing.JButton getBtnJapones() {
        return btnJapones;
    }

    public javax.swing.JButton getBtnTrabajadores() {
        return btnTrabajadores;
    }

    public javax.swing.JLabel getLblCajaimg() {
        return lblCajaimg;
    }

    public javax.swing.JLabel getLblCategoriaimg() {
        return lblCategoriaimg;
    }

    public javax.swing.JLabel getLblClientesimg() {
        return lblClientesimg;
    }

    public javax.swing.JLabel getLblFacturaimg() {
        return lblFacturaimg;
    }

    public javax.swing.JLabel getLblInventarioimg() {
        return lblInventarioimg;
    }

    public javax.swing.JLabel getLblLenguaje() {
        return lblLenguaje;
    }

    public javax.swing.JLabel getLblTrabajadoresimg() {
        return lblTrabajadoresimg;
    }

    public javax.swing.JTabbedPane getPanInformacion() {
        return panInformacion;
    }

    public javax.swing.JTextArea getTxtAcercaDe() {
        return txtAcercaDe;
    }

    public javax.swing.JTextArea getTxtAyudaCaja() {
        return txtAyudaCaja;
    }

    public javax.swing.JTextArea getTxtAyudaCategoria() {
        return txtAyudaCategoria;
    }

    public javax.swing.JTextArea getTxtAyudaClientes() {
        return txtAyudaClientes;
    }

    public javax.swing.JTextArea getTxtAyudaFactura() {
        return txtAyudaFactura;
    }

    public javax.swing.JTextArea getTxtAyudaInventario() {
        return txtAyudaInventario;
    }

    public javax.swing.JTextArea getTxtAyudaTrabajadores() {
        return txtAyudaTrabajadores;
    }
}
