/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Dixi, Vidal y Charlie
 */
public class dlgCategorias extends javax.swing.JDialog {

    
    public dlgCategorias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCategorias = new javax.swing.JTabbedPane();
        pan1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        btnMasDetalles = new javax.swing.JButton();
        btnEliminarCateg = new javax.swing.JButton();
        btnModificarCateg = new javax.swing.JButton();
        btnAnadirCateg = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFiltroCateg = new javax.swing.JTextField();
        pan2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombCateg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdCategoria1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProducCategorias = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreCategAnadir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categorias");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Categoria", "nombre ", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(tblCategorias);

        pan1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 550, 190));

        btnMasDetalles.setText("Mas detalles");
        pan1.add(btnMasDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 180, 30));

        btnEliminarCateg.setText("Eliminar");
        pan1.add(btnEliminarCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 100, 40));

        btnModificarCateg.setText("Modificar");
        pan1.add(btnModificarCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 100, 40));

        btnAnadirCateg.setText("Añadir");
        pan1.add(btnAnadirCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 40));

        jLabel4.setText("Buscar");
        pan1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 20));
        pan1.add(txtFiltroCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, -1));

        panCategorias.addTab("Categorias ", pan1);

        pan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id Categoria");
        pan2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 30));
        pan2.add(txtNombCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 110, 30));

        jLabel2.setText("Nombre :");
        pan2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 60, 30));
        pan2.add(txtIdCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 70, 30));

        jLabel3.setText("Descripcion");
        pan2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 60, 30));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        pan2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 150, 70));

        tblProducCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblProducCategorias);

        pan2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 550, 210));

        panCategorias.addTab("Mas detalles", pan2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, 30));

        jLabel5.setText("Id Categoria");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 80, 30));

        jLabel6.setText("Nombre ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 60, 30));
        jPanel1.add(txtNombreCategAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, 30));

        jLabel7.setText("Descripcioón");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 200, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 140, 40));

        btnCancelar.setText("Cancelar");
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 140, 40));

        btnLimpiar.setText("Limpiar");
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 570, 70));

        panCategorias.addTab("Registro", jPanel1);

        getContentPane().add(panCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgCategorias dialog = new dlgCategorias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirCateg;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarCateg;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMasDetalles;
    private javax.swing.JButton btnModificarCateg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JTabbedPane panCategorias;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTable tblProducCategorias;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFiltroCateg;
    private javax.swing.JTextField txtIdCategoria1;
    private javax.swing.JTextField txtNombCateg;
    private javax.swing.JTextField txtNombreCategAnadir;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnAnadirCateg() {
        return btnAnadirCateg;
    }

    public void setBtnAnadirCateg(javax.swing.JButton btnAnadirCateg) {
        this.btnAnadirCateg = btnAnadirCateg;
    }

    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(javax.swing.JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public javax.swing.JButton getBtnEliminarCateg() {
        return btnEliminarCateg;
    }

    public void setBtnEliminarCateg(javax.swing.JButton btnEliminarCateg) {
        this.btnEliminarCateg = btnEliminarCateg;
    }

    public javax.swing.JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(javax.swing.JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public javax.swing.JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(javax.swing.JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public javax.swing.JButton getBtnMasDetalles() {
        return btnMasDetalles;
    }

    public void setBtnMasDetalles(javax.swing.JButton btnMasDetalles) {
        this.btnMasDetalles = btnMasDetalles;
    }

    public javax.swing.JButton getBtnModificarCateg() {
        return btnModificarCateg;
    }

    public void setBtnModificarCateg(javax.swing.JButton btnModificarCateg) {
        this.btnModificarCateg = btnModificarCateg;
    }

    public javax.swing.JTabbedPane getPanCategorias() {
        return panCategorias;
    }

    public void setPanCategorias(javax.swing.JTabbedPane panCategorias) {
        this.panCategorias = panCategorias;
    }

    public javax.swing.JTable getTblCategorias() {
        return tblCategorias;
    }

    public void setTblCategorias(javax.swing.JTable tblCategorias) {
        this.tblCategorias = tblCategorias;
    }

    public javax.swing.JTable getTblProducCategorias() {
        return tblProducCategorias;
    }

    public void setTblProducCategorias(javax.swing.JTable tblProducCategorias) {
        this.tblProducCategorias = tblProducCategorias;
    }

    public javax.swing.JTextArea getTxtDescripcion() {
        return txtDescripcion;
    }

    public void setTxtDescripcion(javax.swing.JTextArea txtDescripcion) {
        this.txtDescripcion = txtDescripcion;
    }

    public javax.swing.JTextField getTxtFiltroCateg() {
        return txtFiltroCateg;
    }

    public void setTxtFiltroCateg(javax.swing.JTextField txtFiltroCateg) {
        this.txtFiltroCateg = txtFiltroCateg;
    }

    public javax.swing.JTextField getTxtIdCategoria1() {
        return txtIdCategoria1;
    }

    public void setTxtIdCategoria1(javax.swing.JTextField txtIdCategoria1) {
        this.txtIdCategoria1 = txtIdCategoria1;
    }

    public javax.swing.JTextField getTxtNombCateg() {
        return txtNombCateg;
    }

    public void setTxtNombCateg(javax.swing.JTextField txtNombCateg) {
        this.txtNombCateg = txtNombCateg;
    }

    public javax.swing.JTextField getTxtNombreCategAnadir() {
        return txtNombreCategAnadir;
    }

    public void setTxtNombreCategAnadir(javax.swing.JTextField txtNombreCategAnadir) {
        this.txtNombreCategAnadir = txtNombreCategAnadir;
    }
}
