/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author dreads
 */
public class dlgInventario extends javax.swing.JDialog {

    /**
     * Creates new form dlgInventario
     */
    public dlgInventario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panInventario = new javax.swing.JTabbedPane();
        pnlBase = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCalender = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList<>();
        lblCategoria = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        lblProductos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblProveedor = new javax.swing.JLabel();
        lblCateg = new javax.swing.JLabel();
        lblPrecProd = new javax.swing.JLabel();
        lblIdProduct = new javax.swing.JLabel();
        lblnomProd = new javax.swing.JLabel();
        txtNombProductoP = new javax.swing.JTextField();
        txtPrecProductoP = new javax.swing.JTextField();
        txtDescuentoProductoP = new javax.swing.JTextField();
        txtCantidadStockP = new javax.swing.JTextField();
        txtIdProductoP = new javax.swing.JTextField();
        lblDecuent = new javax.swing.JLabel();
        lblProdFragil = new javax.swing.JLabel();
        lblUnidVenta = new javax.swing.JLabel();
        cmbIdCategoria = new javax.swing.JComboBox<>();
        lblCantStock = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripProductoP = new javax.swing.JTextArea();
        rbdNOfragil = new javax.swing.JRadioButton();
        rbdSIfragil = new javax.swing.JRadioButton();
        lblDescrip = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnGuardarProd = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cmbUnidadVenta = new javax.swing.JComboBox<>();
        cmbIdProveedor = new javax.swing.JComboBox<>();
        mnbBarraPrinc = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");
        setMinimumSize(new java.awt.Dimension(800, 491));
        setPreferredSize(new java.awt.Dimension(800, 491));

        pnlBase.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(131, 182, 231));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion (2).png"))); // NOI18N
        jButton1.setText("Ayuda");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion (3).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/engranaje.png"))); // NOI18N
        jButton2.setText("Configuracion");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/engranaje (1).png"))); // NOI18N

        btnCalender.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        btnCalender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario.png"))); // NOI18N
        btnCalender.setText("Calendario");
        btnCalender.setBorderPainted(false);
        btnCalender.setContentAreaFilled(false);
        btnCalender.setDefaultCapable(false);
        btnCalender.setFocusPainted(false);
        btnCalender.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(btnCalender))
                    .addComponent(jButton1))
                .addGap(3, 3, 3))
        );

        lstCategorias.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 14)); // NOI18N
        lstCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstCategorias);

        lblCategoria.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        lblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoria.setText("Seleccione una Categoría");

        tblInventario.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio", "Descuento max", "Stock", "Proveedor"
            }
        ));
        tblInventario.setGridColor(new java.awt.Color(102, 102, 102));
        tblInventario.setRowHeight(20);
        tblInventario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblInventario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblInventario.setShowGrid(true);
        jScrollPane3.setViewportView(tblInventario);

        lblProductos.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        lblProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductos.setText("Productos");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnEliminar.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        btnEditar.setText("Editar");

        btnNuevo.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        btnNuevo.setText("Nuevo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addGroup(pnlBaseLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlBaseLayout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(lblProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(374, 374, 374))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane3)))
                        .addGap(17, 17, 17))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1)
                        .addGap(6, 6, 6))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE))
        );

        panInventario.addTab("Inventario", pnlBase);

        lblProveedor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProveedor.setText("Id Proveedor   :");

        lblCateg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCateg.setText("Id Categoria  :");

        lblPrecProd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPrecProd.setText(" Precio Producto  :");

        lblIdProduct.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblIdProduct.setText(" Id Producto :");

        lblnomProd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblnomProd.setText(" Nombre del Producto :");

        txtIdProductoP.setEditable(false);

        lblDecuent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDecuent.setText("Descuento de Producto :");

        lblProdFragil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProdFragil.setText("Producto Fragil :");

        lblUnidVenta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblUnidVenta.setText("Unidad de Venta ");

        cmbIdCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4" }));

        lblCantStock.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCantStock.setText("Cantida de Stock :");

        txtDescripProductoP.setColumns(20);
        txtDescripProductoP.setRows(5);
        jScrollPane2.setViewportView(txtDescripProductoP);

        buttonGroup1.add(rbdNOfragil);
        rbdNOfragil.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        rbdNOfragil.setText("NO");
        rbdNOfragil.setOpaque(false);

        buttonGroup1.add(rbdSIfragil);
        rbdSIfragil.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        rbdSIfragil.setText("Si");
        rbdSIfragil.setOpaque(false);

        lblDescrip.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDescrip.setText("Descrip de Producto :");

        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarProd.setText("Guardar");
        jPanel4.add(btnGuardarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 50));

        btnCancelar.setText("Cancelar");
        jPanel4.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 220, 50));

        btnLimpiar.setText("Limpiar");
        jPanel4.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 50));

        cmbUnidadVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Unidad", "Kilogramos", "Litros", "Metros ", "Docena" }));

        cmbIdProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "123456", "555555" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtIdProductoP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(cmbIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(cmbIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblnomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(lblDecuent, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(lblDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombProductoP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecProd, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecProductoP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdFragil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbdSIfragil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(rbdNOfragil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescuentoProductoP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUnidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantStock, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadStockP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdProductoP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDecuent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNombProductoP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblPrecProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtPrecProductoP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblProdFragil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbdSIfragil)
                            .addComponent(rbdNOfragil)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDescuentoProductoP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblUnidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cmbUnidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblCantStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtCantidadStockP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panInventario.addTab("Registro ", jPanel3);

        mnbBarraPrinc.setBackground(new java.awt.Color(131, 182, 231));

        jMenu1.setText("Categorias");

        jMenuItem1.setText("herramientas ");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Hogar ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Jardin");
        jMenu1.add(jMenuItem3);

        mnbBarraPrinc.add(jMenu1);

        jMenu2.setText("cajeros");
        mnbBarraPrinc.add(jMenu2);

        jMenu3.setText("Inventario");
        mnbBarraPrinc.add(jMenu3);

        jMenu4.setText("Ventas");

        jMenuItem5.setText("Ventas Diarias");
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Ventas por Semana");
        jMenu4.add(jMenuItem6);

        mnbBarraPrinc.add(jMenu4);

        jMenu5.setText("Historial");
        mnbBarraPrinc.add(jMenu5);

        jMenuItem4.setText("jMenuItem4");
        jMenu6.add(jMenuItem4);

        mnbBarraPrinc.add(jMenu6);

        setJMenuBar(mnbBarraPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panInventario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panInventario)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgInventario dialog = new dlgInventario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalender;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarProd;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbIdCategoria;
    private javax.swing.JComboBox<String> cmbIdProveedor;
    private javax.swing.JComboBox<String> cmbUnidadVenta;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    public javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCantStock;
    private javax.swing.JLabel lblCateg;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDecuent;
    private javax.swing.JLabel lblDescrip;
    private javax.swing.JLabel lblIdProduct;
    private javax.swing.JLabel lblPrecProd;
    private javax.swing.JLabel lblProdFragil;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblUnidVenta;
    private javax.swing.JLabel lblnomProd;
    private javax.swing.JList<String> lstCategorias;
    private javax.swing.JMenuBar mnbBarraPrinc;
    private javax.swing.JTabbedPane panInventario;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JRadioButton rbdNOfragil;
    private javax.swing.JRadioButton rbdSIfragil;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtCantidadStockP;
    private javax.swing.JTextArea txtDescripProductoP;
    private javax.swing.JTextField txtDescuentoProductoP;
    private javax.swing.JTextField txtIdProductoP;
    private javax.swing.JTextField txtNombProductoP;
    private javax.swing.JTextField txtPrecProductoP;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnCalender() {
        return btnCalender;
    }

    public void setBtnCalender(javax.swing.JButton btnCalender) {
        this.btnCalender = btnCalender;
    }

    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(javax.swing.JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public javax.swing.JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(javax.swing.JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(javax.swing.JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public javax.swing.JButton getBtnGuardarProd() {
        return btnGuardarProd;
    }

    public void setBtnGuardarProd(javax.swing.JButton btnGuardarProd) {
        this.btnGuardarProd = btnGuardarProd;
    }

    public javax.swing.JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(javax.swing.JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public javax.swing.JButton getBtnNuevo() {
        return btnNuevo;
    }

    public void setBtnNuevo(javax.swing.JButton btnNuevo) {
        this.btnNuevo = btnNuevo;
    }

    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public javax.swing.JComboBox<String> getCmbIdCategoria() {
        return cmbIdCategoria;
    }

    public void setCmbIdCategoria(javax.swing.JComboBox<String> cmbIdCategoria) {
        this.cmbIdCategoria = cmbIdCategoria;
    }

    public javax.swing.JComboBox<String> getCmbIdProveedor() {
        return cmbIdProveedor;
    }

    public void setCmbIdProveedor(javax.swing.JComboBox<String> cmbIdProveedor) {
        this.cmbIdProveedor = cmbIdProveedor;
    }

    public javax.swing.JComboBox<String> getCmbUnidadVenta() {
        return cmbUnidadVenta;
    }

    public void setCmbUnidadVenta(javax.swing.JComboBox<String> cmbUnidadVenta) {
        this.cmbUnidadVenta = cmbUnidadVenta;
    }

    public javax.swing.JList<String> getLstCategorias() {
        return lstCategorias;
    }

    public void setLstCategorias(javax.swing.JList<String> lstCategorias) {
        this.lstCategorias = lstCategorias;
    }

    public javax.swing.JMenuBar getMnbBarraPrinc() {
        return mnbBarraPrinc;
    }

    public void setMnbBarraPrinc(javax.swing.JMenuBar mnbBarraPrinc) {
        this.mnbBarraPrinc = mnbBarraPrinc;
    }

    public javax.swing.JTabbedPane getPanInventario() {
        return panInventario;
    }

    public void setPanInventario(javax.swing.JTabbedPane panInventario) {
        this.panInventario = panInventario;
    }

    public javax.swing.JRadioButton getRbdNOfragil() {
        return rbdNOfragil;
    }

    public void setRbdNOfragil(javax.swing.JRadioButton rbdNOfragil) {
        this.rbdNOfragil = rbdNOfragil;
    }

    public javax.swing.JRadioButton getRbdSIfragil() {
        return rbdSIfragil;
    }

    public void setRbdSIfragil(javax.swing.JRadioButton rbdSIfragil) {
        this.rbdSIfragil = rbdSIfragil;
    }

    public javax.swing.JTable getTblInventario() {
        return tblInventario;
    }

    public void setTblInventario(javax.swing.JTable tblInventario) {
        this.tblInventario = tblInventario;
    }

    public javax.swing.JTextField getTxtCantidadStockP() {
        return txtCantidadStockP;
    }

    public void setTxtCantidadStockP(javax.swing.JTextField txtCantidadStockP) {
        this.txtCantidadStockP = txtCantidadStockP;
    }

    public javax.swing.JTextArea getTxtDescripProductoP() {
        return txtDescripProductoP;
    }

    public void setTxtDescripProductoP(javax.swing.JTextArea txtDescripProductoP) {
        this.txtDescripProductoP = txtDescripProductoP;
    }

    public javax.swing.JTextField getTxtDescuentoProductoP() {
        return txtDescuentoProductoP;
    }

    public void setTxtDescuentoProductoP(javax.swing.JTextField txtDescuentoProductoP) {
        this.txtDescuentoProductoP = txtDescuentoProductoP;
    }

    public javax.swing.JTextField getTxtIdProductoP() {
        return txtIdProductoP;
    }

    public void setTxtIdProductoP(javax.swing.JTextField txtIdProductoP) {
        this.txtIdProductoP = txtIdProductoP;
    }

    public javax.swing.JTextField getTxtNombProductoP() {
        return txtNombProductoP;
    }

    public void setTxtNombProductoP(javax.swing.JTextField txtNombProductoP) {
        this.txtNombProductoP = txtNombProductoP;
    }

    public javax.swing.JTextField getTxtPrecProductoP() {
        return txtPrecProductoP;
    }

    public void setTxtPrecProductoP(javax.swing.JTextField txtPrecProductoP) {
        this.txtPrecProductoP = txtPrecProductoP;
    }
}
